// Code generated by protoc-gen-grpc-gin. DO NOT EDIT.
// source: user/user.proto

/*
Package user is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package user

import (
	"context"
	"io"

	"github.com/gin-gonic/gin"
	"github.com/hopeio/gox"
	grpc_0 "github.com/hopeio/gox/net/http/grpc"
	"github.com/hopeio/gox/strconv"
	"github.com/hopeio/protobuf/grpc/gateway"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = metadata.Join
var _ = gox.Pointer[bool]
var _ = strconv.Bool

func request_UserService_Signup_0(ctx *gin.Context, client UserServiceClient) (proto.Message, grpc_0.ServerMetadata, error) {
	var protoReq SignupReq
	var md grpc_0.ServerMetadata

	if err := gateway.Bind(ctx, &protoReq); err != nil {
		return nil, md, err
	}

	msg, err := client.Signup(metadata.NewOutgoingContext(ctx.Request.Context(), metadata.MD(ctx.Request.Header)), &protoReq, grpc.Header(&md.Header), grpc.Trailer(&md.Trailer))
	return msg, md, err

}

func local_request_UserService_Signup_0(server UserServiceServer, ctx *gin.Context) (proto.Message, grpc_0.ServerMetadata, error) {
	var stream grpc_0.ServerTransportStream
	var protoReq SignupReq

	if err := gateway.Bind(ctx, &protoReq); err != nil {
		return nil, stream.ServerMetadata(), err
	}

	ctx.Request = ctx.Request.WithContext(grpc.NewContextWithServerTransportStream(metadata.NewIncomingContext(ctx.Request.Context(), metadata.MD(ctx.Request.Header)), &stream))

	resp, err := server.Signup(ctx.Request.Context(), &protoReq)
	return resp, stream.ServerMetadata(), err

}

func request_UserService_GetUser_0(ctx *gin.Context, client UserServiceClient) (proto.Message, grpc_0.ServerMetadata, error) {
	var protoReq GetUserReq
	var md grpc_0.ServerMetadata

	var (
		err error
	)

	protoReq.Id, err = strconv.Uint64(ctx.Param("id"))
	if err != nil {
		return nil, md, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "id", err)
	}

	msg, err := client.GetUser(metadata.NewOutgoingContext(ctx.Request.Context(), metadata.MD(ctx.Request.Header)), &protoReq, grpc.Header(&md.Header), grpc.Trailer(&md.Trailer))
	return msg, md, err

}

func local_request_UserService_GetUser_0(server UserServiceServer, ctx *gin.Context) (proto.Message, grpc_0.ServerMetadata, error) {
	var stream grpc_0.ServerTransportStream
	var protoReq GetUserReq

	ctx.Request = ctx.Request.WithContext(grpc.NewContextWithServerTransportStream(metadata.NewIncomingContext(ctx.Request.Context(), metadata.MD(ctx.Request.Header)), &stream))

	var (
		err error
	)

	protoReq.Id, err = strconv.Uint64(ctx.Param("id"))
	if err != nil {
		return nil, stream.ServerMetadata(), status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "id", err)
	}

	resp, err := server.GetUser(ctx.Request.Context(), &protoReq)
	return resp, stream.ServerMetadata(), err

}

// RegisterUserServiceHandlerServer registers the http handlers for service UserService to "mux".
// UnaryRPC     :call UserServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterUserServiceHandlerFromEndpoint instead.
func RegisterUserServiceHandlerServer(mux *gin.Engine, server UserServiceServer) {

	mux.Handle("POST", "/api/v1/user", func(ctx *gin.Context) {
		resp, md, err := local_request_UserService_Signup_0(server, ctx)
		if err != nil {
			gateway.HttpError(ctx, err)
			return
		}

		gateway.ForwardResponseMessage(ctx, md, resp)

	})

	mux.Handle("GET", "/api/v1/:id", func(ctx *gin.Context) {
		resp, md, err := local_request_UserService_GetUser_0(server, ctx)
		if err != nil {
			gateway.HttpError(ctx, err)
			return
		}

		gateway.ForwardResponseMessage(ctx, md, resp)

	})

}

// RegisterUserServiceHandlerFromEndpoint is same as RegisterUserServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterUserServiceHandlerFromEndpoint(ctx context.Context, mux *gin.Engine, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterUserServiceHandler(ctx, mux, conn)
}

// RegisterUserServiceHandler registers the http handlers for service UserService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterUserServiceHandler(ctx context.Context, mux *gin.Engine, conn *grpc.ClientConn) error {
	return RegisterUserServiceHandlerClient(ctx, mux, NewUserServiceClient(conn))
}

// RegisterUserServiceHandlerClient registers the http handlers for service UserService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "UserServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "UserServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "UserServiceClient" to call the correct interceptors.
func RegisterUserServiceHandlerClient(ctx context.Context, mux *gin.Engine, client UserServiceClient) error {

	mux.Handle("POST", "/api/v1/user", func(ctx *gin.Context) {
		resp, md, err := request_UserService_Signup_0(ctx, client)
		if err != nil {
			gateway.HttpError(ctx, err)
			return
		}

		gateway.ForwardResponseMessage(ctx, md, resp)

	})

	mux.Handle("GET", "/api/v1/:id", func(ctx *gin.Context) {
		resp, md, err := request_UserService_GetUser_0(ctx, client)
		if err != nil {
			gateway.HttpError(ctx, err)
			return
		}

		gateway.ForwardResponseMessage(ctx, md, resp)

	})

	return nil
}
