// Code generated by protoc-gen-grpc-gin. DO NOT EDIT.
// source: user/user.proto

/*
Package user is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package user

import (
	"context"
	"io"

	"github.com/gin-gonic/gin"
	"github.com/hopeio/utils/net/http/gin/binding"
	grpc_0 "github.com/hopeio/utils/net/http/grpc"
	gin_0 "github.com/hopeio/utils/net/http/grpc/gateway/gin"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = grpc_0.String
var _ = metadata.Join

func request_UserService_Signup_0(ctx *gin.Context, client UserServiceClient) (proto.Message, grpc_0.ServerMetadata, error) {
	var protoReq SignupReq
	var metadata grpc_0.ServerMetadata

	if err := binding.Bind(ctx, &protoReq); err != nil {
		return nil, metadata, err
	}

	msg, err := client.Signup(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_UserService_Signup_0(server UserServiceServer, ctx *gin.Context) (proto.Message, error) {
	var protoReq SignupReq

	if err := binding.Bind(ctx, &protoReq); err != nil {
		return nil, err
	}

	return server.Signup(ctx.Request.Context(), &protoReq)

}

// RegisterUserServiceHandlerServer registers the http handlers for service UserService to "mux".
// UnaryRPC     :call UserServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterUserServiceHandlerFromEndpoint instead.
func RegisterUserServiceHandlerServer(mux *gin.Engine, server UserServiceServer) error {

	mux.Handle("POST", "/api/v1/user", func(ctx *gin.Context) {
		var md grpc_0.ServerMetadata
		resp, err := local_request_UserService_Signup_0(server, ctx)
		if err != nil {
			gin_0.HttpError(ctx, err)
			return
		}

		gin_0.ForwardResponseMessage(ctx, md, resp)

	})

	return nil
}

// RegisterUserServiceHandlerFromEndpoint is same as RegisterUserServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterUserServiceHandlerFromEndpoint(ctx context.Context, mux *gin.Engine, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterUserServiceHandler(ctx, mux, conn)
}

// RegisterUserServiceHandler registers the http handlers for service UserService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterUserServiceHandler(ctx context.Context, mux *gin.Engine, conn *grpc.ClientConn) error {
	return RegisterUserServiceHandlerClient(ctx, mux, NewUserServiceClient(conn))
}

// RegisterUserServiceHandlerClient registers the http handlers for service UserService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "UserServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "UserServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "UserServiceClient" to call the correct interceptors.
func RegisterUserServiceHandlerClient(ctx context.Context, mux *gin.Engine, client UserServiceClient) error {

	mux.Handle("POST", "/api/v1/user", func(ctx *gin.Context) {
		resp, md, err := request_UserService_Signup_0(ctx, client)
		if err != nil {
			gin_0.HttpError(ctx, err)
			return
		}

		gin_0.ForwardResponseMessage(ctx, md, resp)

	})

	return nil
}
