// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user/user.proto

package user

import (
	fmt "fmt"
	_ "github.com/danielvladco/go-proto-gql/pkg/graphqlpb"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/hopeio/cherry/protobuf/utils/patch"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *User) Validate() error {
	return nil
}
func (this *SignupReq) Validate() error {
	if !(len(this.Password) > 5) {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`密码最短6位`))
	}
	return nil
}
