// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user/user.enum.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/hopeio/cherry/protobuf/utils/enum"
	_ "github.com/hopeio/cherry/protobuf/utils/patch"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
