// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: user/user.proto

package user

import (
	_ "github.com/danielvladco/go-proto-gql/pkg/graphqlpb"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	deletedAt "github.com/hopeio/protobuf/time/deletedAt"
	timestamp "github.com/hopeio/protobuf/time/timestamp"
	_ "github.com/hopeio/protobuf/utils/enum"
	_ "github.com/hopeio/protobuf/utils/patch"
	_ "github.com/hopeio/protobuf/utils/validator"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户性别
type Gender int32

const (
	GenderPlaceholder Gender = 0
	GenderUnfilled    Gender = 1
	GenderMale        Gender = 2
	GenderFemale      Gender = 3
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GenderPlaceholder",
		1: "GenderUnfilled",
		2: "GenderMale",
		3: "GenderFemale",
	}
	Gender_value = map[string]int32{
		"GenderPlaceholder": 0,
		"GenderUnfilled":    1,
		"GenderMale":        2,
		"GenderFemale":      3,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_user_user_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_user_user_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{0}
}

// 用户角色
type Role int32

const (
	PlaceholderRole Role = 0
	RoleNormal      Role = 1
	RoleAdmin       Role = 2
	RoleSuperAdmin  Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "PlaceholderRole",
		1: "RoleNormal",
		2: "RoleAdmin",
		3: "RoleSuperAdmin",
	}
	Role_value = map[string]int32{
		"PlaceholderRole": 0,
		"RoleNormal":      1,
		"RoleAdmin":       2,
		"RoleSuperAdmin":  3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_user_user_proto_enumTypes[1].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_user_user_proto_enumTypes[1]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{1}
}

// 用户角色
type UserStatus int32

const (
	UserStatusPlaceholder UserStatus = 0
	UserStatusInActive    UserStatus = 1
	UserStatusActivated   UserStatus = 2
	UserStatusFrozen      UserStatus = 3
	UserStatusDeleted     UserStatus = 4
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "UserStatusPlaceholder",
		1: "UserStatusInActive",
		2: "UserStatusActivated",
		3: "UserStatusFrozen",
		4: "UserStatusDeleted",
	}
	UserStatus_value = map[string]int32{
		"UserStatusPlaceholder": 0,
		"UserStatusInActive":    1,
		"UserStatusActivated":   2,
		"UserStatusFrozen":      3,
		"UserStatusDeleted":     4,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_user_proto_enumTypes[2].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_user_user_proto_enumTypes[2]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{2}
}

type UserErr int32

const (
	UserErrPlaceholder  UserErr = 0
	UserErrLogin        UserErr = 1000
	UserErrNoActive     UserErr = 1001
	UserErrNoAuthority  UserErr = 1002
	UserErrLoginTimeout UserErr = 1003
	UserErrInvalidToken UserErr = 1004
	UserErrNoLogin      UserErr = 1005
)

// Enum value maps for UserErr.
var (
	UserErr_name = map[int32]string{
		0:    "UserErrPlaceholder",
		1000: "UserErrLogin",
		1001: "UserErrNoActive",
		1002: "UserErrNoAuthority",
		1003: "UserErrLoginTimeout",
		1004: "UserErrInvalidToken",
		1005: "UserErrNoLogin",
	}
	UserErr_value = map[string]int32{
		"UserErrPlaceholder":  0,
		"UserErrLogin":        1000,
		"UserErrNoActive":     1001,
		"UserErrNoAuthority":  1002,
		"UserErrLoginTimeout": 1003,
		"UserErrInvalidToken": 1004,
		"UserErrNoLogin":      1005,
	}
)

func (x UserErr) Enum() *UserErr {
	p := new(UserErr)
	*p = x
	return p
}

func (x UserErr) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserErr) Descriptor() protoreflect.EnumDescriptor {
	return file_user_user_proto_enumTypes[3].Descriptor()
}

func (UserErr) Type() protoreflect.EnumType {
	return &file_user_user_proto_enumTypes[3]
}

func (x UserErr) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserErr.Descriptor instead.
func (UserErr) EnumDescriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{3}
}

type User struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey;"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" gorm:"size:10;not null" comment:"昵称"`
	Password string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"-" gorm:"size:32;not null" validate:"gte=8,lte=15" comment:"密码"`
	Mail     string                 `protobuf:"bytes,6,opt,name=mail,proto3" json:"mail,omitempty" gorm:"size:32" validate:"email" comment:"邮箱"`
	Phone    string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty" gorm:"size:32" validate:"phone" comment:"手机号"`
	// 性别，0未填写，1男，2女
	Gender        Gender                 `protobuf:"varint,8,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty" gorm:"type:int2;default:0"`
	Role          Role                   `protobuf:"varint,24,opt,name=role,proto3,enum=user.Role" json:"role,omitempty" gorm:"type:int2;default:0"`
	Status        UserStatus             `protobuf:"varint,28,opt,name=status,proto3,enum=user.UserStatus" json:"status,omitempty" gorm:"type:int2;default:0"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,25,opt,name=createdAt,proto3" json:"createdAt,omitempty" gorm:"type:timestamptz(6);default:now();index"`
	ActivatedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=activatedAt,proto3" json:"activatedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"`
	DeletedAt     *deletedAt.DeletedAt   `protobuf:"bytes,27,opt,name=deletedAt,proto3" json:"deletedAt,omitempty" gorm:"<-:false;type:timestamptz(6);index"` // uint32 isDeleted = 29 [(go.field) = {tags:'gorm:"default:0"'}];
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return GenderPlaceholder
}

func (x *User) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return PlaceholderRole
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatusPlaceholder
}

func (x *User) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetActivatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ActivatedAt
	}
	return nil
}

func (x *User) GetDeletedAt() *deletedAt.DeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type SignupReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 密码
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty" validate:"required,gte=6,lte=15" comment:"密码"`
	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" validate:"required,gte=3,lte=10" comment:"昵称"`
	Gender   Gender `protobuf:"varint,3,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty" validate:"required" comment:"性别"`
	// 邮箱
	Mail string `protobuf:"bytes,6,opt,name=mail,proto3" json:"mail,omitempty" validate:"omitempty,email" comment:"邮箱"`
	// 手机号
	Phone string `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty" validate:"omitempty,phone" comment:"手机号"`
	// 验证码
	VCode         string `protobuf:"bytes,8,opt,name=vCode,proto3" json:"vCode,omitempty" validate:"required" comment:"验证码"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupReq) Reset() {
	*x = SignupReq{}
	mi := &file_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupReq) ProtoMessage() {}

func (x *SignupReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupReq.ProtoReflect.Descriptor instead.
func (*SignupReq) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *SignupReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignupReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignupReq) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return GenderPlaceholder
}

func (x *SignupReq) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *SignupReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SignupReq) GetVCode() string {
	if x != nil {
		return x.VCode
	}
	return ""
}

type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey;"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_user_user_proto protoreflect.FileDescriptor

const file_user_user_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/user.proto\x12\x04user\x1a\x1chopeio/utils/enum/enum.proto\x1a\x1bhopeio/utils/patch/go.proto\x1a%hopeio/time/timestamp/timestamp.proto\x1a%hopeio/time/deletedAt/deletedAt.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a&hopeio/utils/validator/validator.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#danielvladco/protobuf/graphql.proto\"\xa9\a\n" +
	"\x04User\x12)\n" +
	"\x02id\x18\x01 \x01(\x04B\x19ҵ\x03\x15\xa2\x01\x12gorm:\"primaryKey;\"R\x02id\x12C\n" +
	"\x04name\x18\x02 \x01(\tB/ҵ\x03+\xa2\x01(gorm:\"size:10;not null\" comment:\"昵称\"R\x04name\x12l\n" +
	"\bpassword\x18\x05 \x01(\tBPҵ\x03L\xa2\x01Ijson:\"-\" gorm:\"size:32;not null\" validate:\"gte=8,lte=15\" comment:\"密码\"R\bpassword\x12K\n" +
	"\x04mail\x18\x06 \x01(\tB7ҵ\x033\xa2\x010gorm:\"size:32\" validate:\"email\" comment:\"邮箱\"R\x04mail\x12P\n" +
	"\x05phone\x18\a \x01(\tB:ҵ\x036\xa2\x013gorm:\"size:32\" validate:\"phone\" comment:\"手机号\"R\x05phone\x12N\n" +
	"\x06gender\x18\b \x01(\x0e2\f.user.GenderB(\x92A\x04\x9a\x02\x01\x03ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06gender\x12A\n" +
	"\x04role\x18\x18 \x01(\x0e2\n" +
	".user.RoleB!ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x04role\x12P\n" +
	"\x06status\x18\x1c \x01(\x0e2\x10.user.UserStatusB&\x92A\x02@\x01ҵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06status\x12i\n" +
	"\tcreatedAt\x18\x19 \x01(\v2\x14.timestamp.TimestampB5ҵ\x031\xa2\x01.gorm:\"type:timestamptz(6);default:now();index\"R\tcreatedAt\x12n\n" +
	"\vactivatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB0ҵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\vactivatedAt\x12d\n" +
	"\tdeletedAt\x18\x1b \x01(\v2\x14.deletedAt.DeletedAtB0ҵ\x03,\xa2\x01)gorm:\"<-:false;type:timestamptz(6);index\"R\tdeletedAt\"\x83\x04\n" +
	"\tSignupReq\x12z\n" +
	"\bpassword\x18\x04 \x01(\tB^\x92A\v*\x06密码\x80\x01\x06ҵ\x034\xa2\x011validate:\"required,gte=6,lte=15\" comment:\"密码\"\xe2\xdf\x1f\x14*\x10密码最短6位p\x05R\bpassword\x12L\n" +
	"\x04name\x18\x01 \x01(\tB8ҵ\x034\xa2\x011validate:\"required,gte=3,lte=10\" comment:\"昵称\"R\x04name\x12Q\n" +
	"\x06gender\x18\x03 \x01(\x0e2\f.user.GenderB+ҵ\x03'\xa2\x01$validate:\"required\" comment:\"性别\"R\x06gender\x12F\n" +
	"\x04mail\x18\x06 \x01(\tB2ҵ\x03.\xa2\x01+validate:\"omitempty,email\" comment:\"邮箱\"R\x04mail\x12K\n" +
	"\x05phone\x18\a \x01(\tB5ҵ\x031\xa2\x01.validate:\"omitempty,phone\" comment:\"手机号\"R\x05phone\x12D\n" +
	"\x05vCode\x18\b \x01(\tB.ҵ\x03*\xa2\x01'validate:\"required\" comment:\"验证码\"R\x05vCode\"7\n" +
	"\n" +
	"GetUserReq\x12)\n" +
	"\x02id\x18\x01 \x01(\x04B\x19ҵ\x03\x15\xa2\x01\x12gorm:\"primaryKey;\"R\x02id*\x7f\n" +
	"\x06Gender\x12!\n" +
	"\x11GenderPlaceholder\x10\x00\x1a\n" +
	"\x92\x9d \x06占位\x12\x1e\n" +
	"\x0eGenderUnfilled\x10\x01\x1a\n" +
	"\x92\x9d \x06未填\x12\x17\n" +
	"\n" +
	"GenderMale\x10\x02\x1a\a\x92\x9d \x03男\x12\x19\n" +
	"\fGenderFemale\x10\x03\x1a\a\x92\x9d \x03女*\x90\x01\n" +
	"\x04Role\x12\x1f\n" +
	"\x0fPlaceholderRole\x10\x00\x1a\n" +
	"\x92\x9d \x06占位\x12 \n" +
	"\n" +
	"RoleNormal\x10\x01\x1a\x10\x92\x9d \f普通用户\x12\x1c\n" +
	"\tRoleAdmin\x10\x02\x1a\r\x92\x9d \t管理员\x12'\n" +
	"\x0eRoleSuperAdmin\x10\x03\x1a\x13\x92\x9d \x0f超级管理员*\xd3\x01\n" +
	"\n" +
	"UserStatus\x12%\n" +
	"\x15UserStatusPlaceholder\x10\x00\x1a\n" +
	"\x92\x9d \x06占位\x12%\n" +
	"\x12UserStatusInActive\x10\x01\x1a\r\x92\x9d \t未激活\x12&\n" +
	"\x13UserStatusActivated\x10\x02\x1a\r\x92\x9d \t已激活\x12#\n" +
	"\x10UserStatusFrozen\x10\x03\x1a\r\x92\x9d \t已冻结\x12$\n" +
	"\x11UserStatusDeleted\x10\x04\x1a\r\x92\x9d \t已注销\x1a\x04\xe0\xa4\x1e\x00*\xb6\x02\n" +
	"\aUserErr\x12\"\n" +
	"\x12UserErrPlaceholder\x10\x00\x1a\n" +
	"\x92\x9d \x06占位\x12/\n" +
	"\fUserErrLogin\x10\xe8\a\x1a\x1c\x92\x9d \x18用户名或密码错误\x12)\n" +
	"\x0fUserErrNoActive\x10\xe9\a\x1a\x13\x92\x9d \x0f未激活账号\x12&\n" +
	"\x12UserErrNoAuthority\x10\xea\a\x1a\r\x92\x9d \t无权限\x12*\n" +
	"\x13UserErrLoginTimeout\x10\xeb\a\x1a\x10\x92\x9d \f登录超时\x12)\n" +
	"\x13UserErrInvalidToken\x10\xec\a\x1a\x0f\x92\x9d \vToken错误\x12\"\n" +
	"\x0eUserErrNoLogin\x10\xed\a\x1a\r\x92\x9d \t未登录\x1a\b\xe0\xa4\x1e\x00\xe8\xa4\x1e\x012\x95\x02\n" +
	"\vUserService\x12\x8b\x01\n" +
	"\x06Signup\x12\x0f.user.SignupReq\x1a\x1c.google.protobuf.StringValue\"R\x92A2\n" +
	"\x12用户相关接口\n" +
	"\x06v1.0.0\x12\x06注册\x1a\f注册接口\xb2\xe0\x1f\x02\b\x01\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/user\x12x\n" +
	"\aGetUser\x12\x10.user.GetUserReq\x1a\n" +
	".user.User\"O\x92A2\n" +
	"\x12用户相关接口\n" +
	"\x06v1.0.0\x12\x06详情\x1a\f详情接口\xb2\xe0\x1f\x02\b\x02\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/{id}Ba\xc8>\x01\x92A\a\x12\x052\x031.0ҵ\x03\x02P\x01\n" +
	"\x1bcherry.hopeio.protobuf.userZ/github.com/hopeio/cherry/_example/protobuf/userb\x06proto3"

var (
	file_user_user_proto_rawDescOnce sync.Once
	file_user_user_proto_rawDescData []byte
)

func file_user_user_proto_rawDescGZIP() []byte {
	file_user_user_proto_rawDescOnce.Do(func() {
		file_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)))
	})
	return file_user_user_proto_rawDescData
}

var file_user_user_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_user_proto_goTypes = []any{
	(Gender)(0),                    // 0: user.Gender
	(Role)(0),                      // 1: user.Role
	(UserStatus)(0),                // 2: user.UserStatus
	(UserErr)(0),                   // 3: user.UserErr
	(*User)(nil),                   // 4: user.User
	(*SignupReq)(nil),              // 5: user.SignupReq
	(*GetUserReq)(nil),             // 6: user.GetUserReq
	(*timestamp.Timestamp)(nil),    // 7: timestamp.Timestamp
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
	(*deletedAt.DeletedAt)(nil),    // 9: deletedAt.DeletedAt
	(*wrapperspb.StringValue)(nil), // 10: google.protobuf.StringValue
}
var file_user_user_proto_depIdxs = []int32{
	0,  // 0: user.User.gender:type_name -> user.Gender
	1,  // 1: user.User.role:type_name -> user.Role
	2,  // 2: user.User.status:type_name -> user.UserStatus
	7,  // 3: user.User.createdAt:type_name -> timestamp.Timestamp
	8,  // 4: user.User.activatedAt:type_name -> google.protobuf.Timestamp
	9,  // 5: user.User.deletedAt:type_name -> deletedAt.DeletedAt
	0,  // 6: user.SignupReq.gender:type_name -> user.Gender
	5,  // 7: user.UserService.Signup:input_type -> user.SignupReq
	6,  // 8: user.UserService.GetUser:input_type -> user.GetUserReq
	10, // 9: user.UserService.Signup:output_type -> google.protobuf.StringValue
	4,  // 10: user.UserService.GetUser:output_type -> user.User
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_user_user_proto_init() }
func file_user_user_proto_init() {
	if File_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_proto_goTypes,
		DependencyIndexes: file_user_user_proto_depIdxs,
		EnumInfos:         file_user_user_proto_enumTypes,
		MessageInfos:      file_user_user_proto_msgTypes,
	}.Build()
	File_user_user_proto = out.File
	file_user_user_proto_goTypes = nil
	file_user_user_proto_depIdxs = nil
}
