// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/user.proto

package user

import (
	_ "github.com/alta/protopatch/patch/gopb"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/hopeio/protobuf/time/timestamp"
	_ "github.com/hopeio/protobuf/utils/validator"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户性别
type Gender int32

const (
	Gender_GenderPlaceholder Gender = 0
	Gender_GenderUnfilled    Gender = 1
	Gender_GenderMale        Gender = 2
	Gender_GenderFemale      Gender = 3
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GenderPlaceholder",
		1: "GenderUnfilled",
		2: "GenderMale",
		3: "GenderFemale",
	}
	Gender_value = map[string]int32{
		"GenderPlaceholder": 0,
		"GenderUnfilled":    1,
		"GenderMale":        2,
		"GenderFemale":      3,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_proto_user_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

// 用户角色
type Role int32

const (
	Role_PlaceholderRole Role = 0
	Role_RoleNormal      Role = 1
	Role_RoleAdmin       Role = 2
	Role_RoleSuperAdmin  Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "PlaceholderRole",
		1: "RoleNormal",
		2: "RoleAdmin",
		3: "RoleSuperAdmin",
	}
	Role_value = map[string]int32{
		"PlaceholderRole": 0,
		"RoleNormal":      1,
		"RoleAdmin":       2,
		"RoleSuperAdmin":  3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_proto_enumTypes[1].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_proto_user_proto_enumTypes[1]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

// 用户角色
type UserStatus int32

const (
	UserStatus_UserStatusPlaceholder UserStatus = 0
	UserStatus_UserStatusInActive    UserStatus = 1
	UserStatus_UserStatusActivated   UserStatus = 2
	UserStatus_UserStatusFrozen      UserStatus = 3
	UserStatus_UserStatusDeleted     UserStatus = 4
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "UserStatusPlaceholder",
		1: "UserStatusInActive",
		2: "UserStatusActivated",
		3: "UserStatusFrozen",
		4: "UserStatusDeleted",
	}
	UserStatus_value = map[string]int32{
		"UserStatusPlaceholder": 0,
		"UserStatusInActive":    1,
		"UserStatusActivated":   2,
		"UserStatusFrozen":      3,
		"UserStatusDeleted":     4,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_proto_enumTypes[2].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_proto_user_proto_enumTypes[2]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{2}
}

type UserErr int32

const (
	UserErr_UserErrPlaceholder  UserErr = 0
	UserErr_UserErrLogin        UserErr = 1000
	UserErr_UserErrNoActive     UserErr = 1001
	UserErr_UserErrNoAuthority  UserErr = 1002
	UserErr_UserErrLoginTimeout UserErr = 1003
	UserErr_UserErrInvalidToken UserErr = 1004
	UserErr_UserErrNoLogin      UserErr = 1005
)

// Enum value maps for UserErr.
var (
	UserErr_name = map[int32]string{
		0:    "UserErrPlaceholder",
		1000: "UserErrLogin",
		1001: "UserErrNoActive",
		1002: "UserErrNoAuthority",
		1003: "UserErrLoginTimeout",
		1004: "UserErrInvalidToken",
		1005: "UserErrNoLogin",
	}
	UserErr_value = map[string]int32{
		"UserErrPlaceholder":  0,
		"UserErrLogin":        1000,
		"UserErrNoActive":     1001,
		"UserErrNoAuthority":  1002,
		"UserErrLoginTimeout": 1003,
		"UserErrInvalidToken": 1004,
		"UserErrNoLogin":      1005,
	}
)

func (x UserErr) Enum() *UserErr {
	p := new(UserErr)
	*p = x
	return p
}

func (x UserErr) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserErr) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_user_proto_enumTypes[3].Descriptor()
}

func (UserErr) Type() protoreflect.EnumType {
	return &file_proto_user_proto_enumTypes[3]
}

func (x UserErr) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserErr.Descriptor instead.
func (UserErr) EnumDescriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{3}
}

type User struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey;"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" gorm:"size:10;not null" comment:"昵称"`
	Password string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"-" gorm:"size:32;not null" validate:"gte=8,lte=15" comment:"密码"`
	Mail     string                 `protobuf:"bytes,6,opt,name=mail,proto3" json:"mail,omitempty" gorm:"size:32" validate:"email" comment:"邮箱"`
	Phone    string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty" gorm:"size:32" validate:"phone" comment:"手机号"`
	// 性别，0未填写，1男，2女
	Gender        Gender     `protobuf:"varint,8,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty" gorm:"type:int2;default:0"`
	Role          Role       `protobuf:"varint,24,opt,name=role,proto3,enum=user.Role" json:"role,omitempty" gorm:"type:int2;default:0"`
	Status        UserStatus `protobuf:"varint,28,opt,name=status,proto3,enum=user.UserStatus" json:"status,omitempty" gorm:"type:int2;default:0"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GenderPlaceholder
}

func (x *User) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_PlaceholderRole
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_UserStatusPlaceholder
}

type SignupReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 密码
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty" validate:"required,gte=6,lte=15" comment:"密码"`
	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" validate:"required,gte=3,lte=10" comment:"昵称"`
	Gender   Gender `protobuf:"varint,3,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty" validate:"required" comment:"性别"`
	// 邮箱
	Mail string `protobuf:"bytes,6,opt,name=mail,proto3" json:"mail,omitempty" validate:"omitempty,email" comment:"邮箱"`
	// 手机号
	Phone string `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty" validate:"omitempty,phone" comment:"手机号"`
	// 验证码
	VCode         string `protobuf:"bytes,8,opt,name=vCode,proto3" json:"vCode,omitempty" validate:"required" comment:"验证码"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupReq) Reset() {
	*x = SignupReq{}
	mi := &file_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupReq) ProtoMessage() {}

func (x *SignupReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupReq.ProtoReflect.Descriptor instead.
func (*SignupReq) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *SignupReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignupReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignupReq) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GenderPlaceholder
}

func (x *SignupReq) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *SignupReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SignupReq) GetVCode() string {
	if x != nil {
		return x.VCode
	}
	return ""
}

type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey;"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_user_proto protoreflect.FileDescriptor

const file_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x10proto/user.proto\x12\x04user\x1a\x0epatch/go.proto\x1a%hopeio/time/timestamp/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a&hopeio/utils/validator/validator.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x04\n" +
	"\x04User\x12)\n" +
	"\x02id\x18\x01 \x01(\x04B\x19ʵ\x03\x15\xa2\x01\x12gorm:\"primaryKey;\"R\x02id\x12C\n" +
	"\x04name\x18\x02 \x01(\tB/ʵ\x03+\xa2\x01(gorm:\"size:10;not null\" comment:\"昵称\"R\x04name\x12l\n" +
	"\bpassword\x18\x05 \x01(\tBPʵ\x03L\xa2\x01Ijson:\"-\" gorm:\"size:32;not null\" validate:\"gte=8,lte=15\" comment:\"密码\"R\bpassword\x12K\n" +
	"\x04mail\x18\x06 \x01(\tB7ʵ\x033\xa2\x010gorm:\"size:32\" validate:\"email\" comment:\"邮箱\"R\x04mail\x12P\n" +
	"\x05phone\x18\a \x01(\tB:ʵ\x036\xa2\x013gorm:\"size:32\" validate:\"phone\" comment:\"手机号\"R\x05phone\x12N\n" +
	"\x06gender\x18\b \x01(\x0e2\f.user.GenderB(\x92A\x04\x9a\x02\x01\x03ʵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06gender\x12A\n" +
	"\x04role\x18\x18 \x01(\x0e2\n" +
	".user.RoleB!ʵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x04role\x12P\n" +
	"\x06status\x18\x1c \x01(\x0e2\x10.user.UserStatusB&\x92A\x02@\x01ʵ\x03\x1d\xa2\x01\x1agorm:\"type:int2;default:0\"R\x06status\"\x83\x04\n" +
	"\tSignupReq\x12z\n" +
	"\bpassword\x18\x04 \x01(\tB^\x92A\v*\x06密码\x80\x01\x06ʵ\x034\xa2\x011validate:\"required,gte=6,lte=15\" comment:\"密码\"\xe2\xdf\x1f\x14*\x10密码最短6位p\x05R\bpassword\x12L\n" +
	"\x04name\x18\x01 \x01(\tB8ʵ\x034\xa2\x011validate:\"required,gte=3,lte=10\" comment:\"昵称\"R\x04name\x12Q\n" +
	"\x06gender\x18\x03 \x01(\x0e2\f.user.GenderB+ʵ\x03'\xa2\x01$validate:\"required\" comment:\"性别\"R\x06gender\x12F\n" +
	"\x04mail\x18\x06 \x01(\tB2ʵ\x03.\xa2\x01+validate:\"omitempty,email\" comment:\"邮箱\"R\x04mail\x12K\n" +
	"\x05phone\x18\a \x01(\tB5ʵ\x031\xa2\x01.validate:\"omitempty,phone\" comment:\"手机号\"R\x05phone\x12D\n" +
	"\x05vCode\x18\b \x01(\tB.ʵ\x03*\xa2\x01'validate:\"required\" comment:\"验证码\"R\x05vCode\"7\n" +
	"\n" +
	"GetUserReq\x12)\n" +
	"\x02id\x18\x01 \x01(\x04B\x19ʵ\x03\x15\xa2\x01\x12gorm:\"primaryKey;\"R\x02id*U\n" +
	"\x06Gender\x12\x15\n" +
	"\x11GenderPlaceholder\x10\x00\x12\x12\n" +
	"\x0eGenderUnfilled\x10\x01\x12\x0e\n" +
	"\n" +
	"GenderMale\x10\x02\x12\x10\n" +
	"\fGenderFemale\x10\x03*N\n" +
	"\x04Role\x12\x13\n" +
	"\x0fPlaceholderRole\x10\x00\x12\x0e\n" +
	"\n" +
	"RoleNormal\x10\x01\x12\r\n" +
	"\tRoleAdmin\x10\x02\x12\x12\n" +
	"\x0eRoleSuperAdmin\x10\x03*\x85\x01\n" +
	"\n" +
	"UserStatus\x12\x19\n" +
	"\x15UserStatusPlaceholder\x10\x00\x12\x16\n" +
	"\x12UserStatusInActive\x10\x01\x12\x17\n" +
	"\x13UserStatusActivated\x10\x02\x12\x14\n" +
	"\x10UserStatusFrozen\x10\x03\x12\x15\n" +
	"\x11UserStatusDeleted\x10\x04*\xac\x01\n" +
	"\aUserErr\x12\x16\n" +
	"\x12UserErrPlaceholder\x10\x00\x12\x11\n" +
	"\fUserErrLogin\x10\xe8\a\x12\x14\n" +
	"\x0fUserErrNoActive\x10\xe9\a\x12\x17\n" +
	"\x12UserErrNoAuthority\x10\xea\a\x12\x18\n" +
	"\x13UserErrLoginTimeout\x10\xeb\a\x12\x18\n" +
	"\x13UserErrInvalidToken\x10\xec\a\x12\x13\n" +
	"\x0eUserErrNoLogin\x10\xed\a2\x83\x02\n" +
	"\vUserService\x12\x82\x01\n" +
	"\x06Signup\x12\x0f.user.SignupReq\x1a\x1c.google.protobuf.StringValue\"I\x92A2\n" +
	"\x12用户相关接口\n" +
	"\x06v1.0.0\x12\x06注册\x1a\f注册接口\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/api/user\x12o\n" +
	"\aGetUser\x12\x10.user.GetUserReq\x1a\n" +
	".user.User\"F\x92A2\n" +
	"\x12用户相关接口\n" +
	"\x06v1.0.0\x12\x06详情\x1a\f详情接口\x82\xd3\xe4\x93\x02\v\x12\t/api/{id}BX\x92A\a\x12\x052\x031.0\n" +
	"\x1bmix.hopeio.protobuf.userZ/github.com/hopeio/mix/_example/protobuf/userb\x06proto3"

var (
	file_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_rawDescData []byte
)

func file_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)))
	})
	return file_proto_user_proto_rawDescData
}

var file_proto_user_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_user_proto_goTypes = []any{
	(Gender)(0),                    // 0: user.Gender
	(Role)(0),                      // 1: user.Role
	(UserStatus)(0),                // 2: user.UserStatus
	(UserErr)(0),                   // 3: user.UserErr
	(*User)(nil),                   // 4: user.User
	(*SignupReq)(nil),              // 5: user.SignupReq
	(*GetUserReq)(nil),             // 6: user.GetUserReq
	(*wrapperspb.StringValue)(nil), // 7: google.protobuf.StringValue
}
var file_proto_user_proto_depIdxs = []int32{
	0, // 0: user.User.gender:type_name -> user.Gender
	1, // 1: user.User.role:type_name -> user.Role
	2, // 2: user.User.status:type_name -> user.UserStatus
	0, // 3: user.SignupReq.gender:type_name -> user.Gender
	5, // 4: user.UserService.Signup:input_type -> user.SignupReq
	6, // 5: user.UserService.GetUser:input_type -> user.GetUserReq
	7, // 6: user.UserService.Signup:output_type -> google.protobuf.StringValue
	4, // 7: user.UserService.GetUser:output_type -> user.User
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_user_proto_init() }
func file_proto_user_proto_init() {
	if File_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_depIdxs,
		EnumInfos:         file_proto_user_proto_enumTypes,
		MessageInfos:      file_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto = out.File
	file_proto_user_proto_goTypes = nil
	file_proto_user_proto_depIdxs = nil
}
