apiVersion: v1
kind: Service
metadata:
  name: debug-svc
  namespace: default
  labels:
    app: debug-app
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      nodePort: 10666
    - name: http
      port: 2345
      protocol: TCP
      nodePort: 12345
  selector:
    app: debug-app