
[Log]
DisableCaller = false
DisableStacktrace = false
EncodeLevelType = ""
ErrorOutputPaths = []
Level = "debug"

[Log.EncoderConfig]
CallerKey = ""
ConsoleSeparator = ""
FunctionKey = ""
LevelKey = ""
LineEnding = ""
MessageKey = ""
NameKey = ""
SkipLineEnding = false
StacktraceKey = ""
TimeKey = ""

[Log.OutputPaths]
Console = ["stdout"]
Json = []


[Server]
CertFile = ""
EnableCors = true
EnableGrpcWeb = true
GenDoc = false
KeyFile = ""
Prometheus = true
StopTimeout = "5s"
Tracing = true
Metrics = true

[Server.Http]
Addr = ":8080"
ReadTimeout = "60s"
WriteTimeout = "60s"
[Server.HttpOptions]
ExcludeLogPrefixes = ["/api/v1/upload", "/api/v1/multiUpload", "/api/ws/chat"]
IncludeLogPrefixes = ["/api"]

[Server.Gin]
ContextWithFallback = true

[Redis]
Addr = 'xxx'
DialTimeout = "20s"
IdleTimeout = "20s"
MaxConnAge = 10
MaxRetries = 10
MinIdleConns = 1
Password = 'xxx'
PoolFIFO = false
PoolSize = 5
PoolTimeout = "1s"
ReadTimeout = "20s"
WriteTimeout = "20s"

[GORMDB]
Charset = "utf8"
Database = "cute"
EnablePrometheus = false
EnableStdLogger = true
Host = "xxx"
MaxIdleConns = 10
MaxOpenConns = 10
Password = "xxx"
Port = 5432
Schema = ""
TimeFormat = ""
TimeZone = ""
Type = "postgres"
User = "xxx"

[GORMDB.Logger]
Colorful = true
IgnoreRecordNotFoundError = false
LogLevel = 4
ParameterizedQueries = false
SlowThreshold = "200ms"

[GORMDB.NamingStrategy]
SingularTable = true