ARG IMAGE=golang:latest

FROM ${IMAGE}

ENV PATH /protoc/bin:$PATH

ADD ./protoc-gen-enum /bin/
ADD ./protoc-gen-go /bin/
ADD ./protoc-gen-go-grpc /bin/
ADD ./protoc-gen-go-patch /bin/
ADD ./protoc-gen-validator /bin/
ADD ./protoc-gen-grpc-gateway /bin/
ADD ./protoc-gen-grpc-gin /bin/
ADD ./protoc-gen-openapiv2 /bin/
ADD ./protoc-gen-gql /bin/
ADD ./protoc-gen-gogql /bin/
ADD ./gqlgen /bin/
ADD ./protogen /bin/
ADD ./_proto/ /proto/
ADD ./protoc/ /protoc/

WORKDIR /work

