ARG IMAGE=golang:latest

# Builder Image
FROM jybl/protogen AS source

FROM ${IMAGE} AS upgrade

ENV PATH=/protoc/bin:$PATH

COPY --from=source /bin/protoc-gen-enum /bin/
COPY --from=source /bin/protoc-gen-go /bin/
COPY --from=source /bin/protoc-gen-go-grpc /bin/
COPY --from=source /bin/protoc-gen-go-patch /bin/
COPY --from=source /bin/protoc-gen-validator /bin/
COPY --from=source /bin/protoc-gen-grpc-gateway /bin/
COPY --from=source /bin/protoc-gen-grpc-gin /bin/
COPY --from=source /bin/protoc-gen-openapiv2 /bin/
COPY --from=source /bin/protoc-gen-gql /bin/
COPY --from=source /bin/protoc-gen-gogql /bin/
COPY --from=source /bin/gqlgen /bin/
COPY --from=source /bin/protogen /bin/
COPY --from=source /proto/ /proto/
COPY --from=source /protoc/ /protoc/

WORKDIR /work